논리 연산 결과를 이용한 배열 원소 선택

In [1]:
import numpy as np

아래 예에서 배열 names의 원소는 모두 7개이며, 각 원소는 배열 data의 행(row)에 대응된다고 가정.

In [4]:
names = np.array(['Kim', 'Lee', 'Park', 'Kim', 'Park', 'Lee', 'Lee'])
data = np.random.randn(7,4)

In [5]:
names  

array(['Kim', 'Lee', 'Park', 'Kim', 'Park', 'Lee', 'Lee'], dtype='<U4')

In [6]:
data

array([[ 0.48408458,  1.24158315,  1.24129628,  0.47844047],
       [ 0.01351501, -0.3823599 , -0.20404109, -0.87467514],
       [ 0.68669715,  0.19150034, -0.8000639 ,  0.42169539],
       [ 0.27083698,  0.22715289, -0.36498433,  1.474622  ],
       [-0.34285793, -0.76967845, -2.40397905,  0.56079246],
       [ 0.041964  ,  0.41468742,  0.0697782 , -0.66825039],
       [-0.57673388,  0.46331817,  0.34054792, -0.23458025]])

배열 data에서 'Kim'에 대응되는 행(row)인 0, 3을 찾고 싶다. 'Lee'는 행 1,5,6, 'Park'은 행 2,4.

In [7]:
names == 'Kim'

array([ True, False, False,  True, False, False, False])

In [8]:
data[names == 'Kim']

array([[ 0.48408458,  1.24158315,  1.24129628,  0.47844047],
       [ 0.27083698,  0.22715289, -0.36498433,  1.474622  ]])

In [9]:
data[names == 'Kim', 2:]
#data[names == 'Kim', 3]

array([[ 1.24129628,  0.47844047],
       [-0.36498433,  1.474622  ]])

In [10]:
names != 'Kim'
#~(names == 'Kim')

array([False,  True,  True, False,  True,  True,  True])

In [11]:
data[~(names == 'Kim')]

array([[ 0.01351501, -0.3823599 , -0.20404109, -0.87467514],
       [ 0.68669715,  0.19150034, -0.8000639 ,  0.42169539],
       [-0.34285793, -0.76967845, -2.40397905,  0.56079246],
       [ 0.041964  ,  0.41468742,  0.0697782 , -0.66825039],
       [-0.57673388,  0.46331817,  0.34054792, -0.23458025]])

In [12]:
cond = names == 'Kim'
data[~cond]

array([[ 0.01351501, -0.3823599 , -0.20404109, -0.87467514],
       [ 0.68669715,  0.19150034, -0.8000639 ,  0.42169539],
       [-0.34285793, -0.76967845, -2.40397905,  0.56079246],
       [ 0.041964  ,  0.41468742,  0.0697782 , -0.66825039],
       [-0.57673388,  0.46331817,  0.34054792, -0.23458025]])

논리 AND('&') 및 논리 OR('|') 연산

In [13]:
mask = (names == 'Kim') | (names == 'Park')
mask

array([ True, False,  True,  True,  True, False, False])

In [46]:
data[mask]

array([[ 0.20176935,  0.54716886, -0.60680992, -0.47619612],
       [ 2.15055524,  0.6947555 ,  0.48922107,  0.20627865],
       [ 0.82791769, -1.34121766,  0.06292382, -1.96297453],
       [ 0.465281  , -2.70274869, -0.59503503, -0.59036535]])

In [47]:
data[data<0] = 0  # 모든 음수 값을 0으로 바꿈
data

array([[0.20176935, 0.54716886, 0.        , 0.        ],
       [0.        , 2.00301093, 0.        , 0.        ],
       [2.15055524, 0.6947555 , 0.48922107, 0.20627865],
       [0.82791769, 0.        , 0.06292382, 0.        ],
       [0.465281  , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.28686563, 0.        ],
       [0.        , 0.        , 0.        , 1.01648602]])

In [14]:
data[names != 'Lee'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.01351501, -0.3823599 , -0.20404109, -0.87467514],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.041964  ,  0.41468742,  0.0697782 , -0.66825039],
       [-0.57673388,  0.46331817,  0.34054792, -0.23458025]])