배열=행렬: 행렬 전치(transpose) 및 행렬 내적(inner product)

In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [4]:
arr = np.random.randn(6,3)
arr

array([[ 1.27977043,  0.8248648 , -0.17004237],
       [-1.21474206, -0.63224931, -0.06814982],
       [-0.02003068, -0.03263793,  1.04386319],
       [-0.5080594 ,  0.66973247,  0.57413274],
       [-2.06829788, -0.539668  ,  0.42635904],
       [-0.21614384, -0.31200759, -1.9820498 ]])

In [5]:
np.dot(arr.T, arr)  # 3x6 dot 6x3 = 3x3
#np.dot(arr, arr.T) # 6x3 dot 3x6 = 6x6

array([[ 7.69651048,  2.66768   , -0.90086322],
       [ 2.66768   ,  1.91833823,  0.64159376],
       [-0.90086322,  0.64159376,  5.563141  ]])

배열 원소에 대한 통계 연산(sum, mean, std 등)을 해 보자!

In [9]:
arr = np.random.randn(5,4)
arr

array([[-0.20197062,  0.27605099,  0.39514605,  0.94095141],
       [-0.66593587, -1.64246847,  1.01274435, -1.2027671 ],
       [-0.69221688,  0.19043971,  0.14100782, -0.9736881 ],
       [ 1.10941057,  0.0519215 ,  1.61619553, -0.691129  ],
       [ 0.54512781,  1.60682879, -0.36708215,  0.84095806]])

In [10]:
arr.mean()
#np.mean(arr)

0.11447622071453267

In [11]:
arr.sum()

2.2895244142906535

In [12]:
arr.mean(axis=1) # 행(row) 단위로 평균을 구함

array([ 0.35254446, -0.62460677, -0.33361436,  0.52159965,  0.65645813])

In [13]:
arr.sum(axis=0) # 열(column) 단위로 평균을 구함

array([ 0.09441501,  0.48277253,  2.79801161, -1.08567473])

1차 배열의 경우 누적 합(cumsum), 누적 곱(cumprod)은 같은 크기의 배열을 생성.

In [14]:
arr = np.array([1,2,3,4,5,6,7,8])

In [15]:
arr.cumsum()
#arr.cumprod()

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [16]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [18]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

이제 numpy의 where 구문을 사용해서 구현해 보자!

In [19]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [20]:
result = [(x if c else y)
           for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [21]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [22]:
arr = np.random.randn(4,4)
arr

array([[-0.62098105, -0.96090842, -0.03242148,  0.91203747],
       [ 0.29125527, -0.66424242, -0.95391239,  1.37427581],
       [ 0.32789797,  0.20383611, -0.96940648,  1.43351042],
       [-1.34200108,  0.9434992 ,  0.04350907, -0.81567014]])

In [23]:
arr > 0

array([[False, False, False,  True],
       [ True, False, False,  True],
       [ True,  True, False,  True],
       [False,  True,  True, False]])

In [24]:
np.where(arr>0, 2, -2)

array([[-2, -2, -2,  2],
       [ 2, -2, -2,  2],
       [ 2,  2, -2,  2],
       [-2,  2,  2, -2]])

In [25]:
np.where(arr>0, 2, arr) # where 구문의 parameter는 scalar이거나 배열

array([[-0.62098105, -0.96090842, -0.03242148,  2.        ],
       [ 2.        , -0.66424242, -0.95391239,  2.        ],
       [ 2.        ,  2.        , -0.96940648,  2.        ],
       [-1.34200108,  2.        ,  2.        , -0.81567014]])