numpy는 대규모 배열 처리에 효율적. 처리 속도도 python에 비해 10~100배 이상 빠름.

In [1]:
import numpy as np

In [5]:
np.arange(10) #numpy 1차원 배열 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
range(10) #python 1차원 배열

range(0, 10)

In [2]:
my_arr = np.arange(1000000)  #numpy 1차원 배열 - 원소 개수 100만개
my_list = list(range(1000000)) #python 1차원 배열

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 26 ms


In [4]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 846 ms


numpy 기초: n차원 배열(ndarray) - 원소의 type은 같음. ndarray는 같은 형을 갖는 원소로 이루어진 배열.

In [7]:
np.random.randn() # 크기를 지정하지 않으면 1개의 랜덤 숫자(float) 반환.

1.169958761734319

In [8]:
data = np.random.randn(2,3)  # 2x3 실수 배열, randn :정규분포로부터 랜덤 숫자(float) 생성
data

array([[ 0.45236708,  0.92352714,  0.86379993],
       [-0.09183868, -0.09052638,  0.77372605]])

In [13]:
type(data)
#data.shape  # 몇 차원 배열인가? 
#data.dtype  # 배열의 원소의 type은?
#data.ndim # 몇 차원 배열인가?

numpy.ndarray

In [14]:
data * 10

array([[-17.10468057,   3.26239462,   4.18196541],
       [  6.73347433,   0.64434161, -15.29809202]])

In [15]:
data + data

array([[-3.42093611,  0.65247892,  0.83639308],
       [ 1.34669487,  0.12886832, -3.0596184 ]])

randn의 n은 정규 분포(normal distribution) : 평균-0, 표준편차-1

In [17]:
arr = np.random.randn(100)
arr2 = np.random.randn(1000)
arr3 = np.random.randn(10000)

In [18]:
print(arr.mean(), arr.std())
print(arr2.mean(), arr2.std())
print(arr3.mean(), arr3.std())

0.046220228467555205 1.0376636413690383
0.02809673178875582 1.015402184950163
0.001366236873157409 1.0051887436247795


numpy 배열 ndarray 생성  

In [19]:
#array 함수 사용: python의 리스트를 1차원 배열로 변환
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
#ndarray를 생성할 때 type을 추론 -> 7.5 -> 모든 원소의 type은 float64
#ndarray에 속한 모든 원소의 타입은 같아야 함.
arr1.dtype  

dtype('float64')

In [22]:
arr1.shape
#arr1.ndim   #몇 차원 배열인가?

(5,)

In [23]:
#array 함수 사용: python의 다중 리스트를 2차원 배열로 변환
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr2.shape
#arr2.ndim
#arr2.dtype # ndarray를 생성할 때 type을 추론 -> 모든 원소의 type은 int32

(2, 4)

np.linspace, np.logspace, np.diag함수를 사용한 ndarray 생성 

In [26]:
np.linspace(0, 10, 25) #0~10사이의 값 25개 생성

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [27]:
np.logspace(0,10,10, base=np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [28]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

numpy 배열을 생성하기 위한 함수들: ones, zeros, empty, eye, identity 등

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [44]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

ndarray 차원 변환 : reshape 

In [29]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])