In [4]:
import re
import csv
import json
import numpy as np
import pandas as pd
import tensorflow as tf
from konlpy.tag import Okt

from tensorflow.python.keras.preprocessing.text import Tokenizer

ModuleNotFoundError: No module named 'tensorflow'

In [2]:
DATA_IN_PATH = './data_in/'
train_file = DATA_IN_PATH + 'ratings_train.txt'
train_data = pd.read_csv(train_file, header=0, delimiter='\t', quoting=csv.QUOTE_NONE)

In [4]:
train_data.head()

id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [6]:
# 정규표현(re)을 사용해 아래에 해당하지 않는 기호는 모두 제거
# 한글음절 :음절 11,174자 ('가'-'힣'), 자음('ㄱ'-'ㅎ'), 모음('ㅏ'-'ㅣ'), whitespace char(\s)
print(train_data['document'][0])
review_text = re.sub('[^가-힣ㄱ-ㅎㅏ-ㅣ\\s]', '', train_data['document'][0])
print(review_text)

아 더빙.. 진짜 짜증나네요 목소리
아 더빙 진짜 짜증나네요 목소리


In [7]:
print(review_text)
okt = Okt()
review_text = okt.morphs(review_text, stem=True)
print(review_text)

아 더빙 진짜 짜증나네요 목소리
['아', '더빙', '진짜', '짜증나다', '목소리']


In [10]:
with open('./kr_stopwords.txt', encoding='utf8') as f:
    stopwords = f.readlines()
stopwords = [x.strip() for x in stopwords]    
print(stopwords[:10])

['아', '휴', '아이구', '아이쿠', '아이고', '어', '나', '우리', '저희', '따라']


In [12]:
print(review_text)
revised_text = [w for w in review_text if len(w) > 1]
clean_review = [w for w in revised_text if not w in stopwords]
print(clean_review)

['아', '더빙', '진짜', '짜증나다', '목소리']
['더빙', '진짜', '짜증나다', '목소리']


In [19]:
def preprocessing(review, remove_stopwords, stop_words):
    review_text = re.sub('[^가-힣ㄱ-ㅎㅏ-ㅣ\\s]', '', review)
    word_review = okt.morphs(review_text, stem=True)
    
    if remove_stopwords:
        revised_text = [w for w in word_review if len(w) > 1]
        word_review = [token for token in revised_text 
                       if not token in stop_words]
        
    return word_review

In [28]:
clean_train_review = []

i = 0
max = len(train_data['document'])
for review in train_data['document']:
    if (i % 1500 == 0):
        print('진행률= %d 퍼센트' % ((i/max * 100)+1))
    if type(review) == str:
        clean_train_review.append(preprocessing(review, True, stopwords))
    else:
        clean_train_review.append([])
    i += 1

진행률= 0 퍼센트
진행률= 1 퍼센트
진행률= 2 퍼센트
진행률= 3 퍼센트
진행률= 4 퍼센트
진행률= 5 퍼센트
진행률= 6 퍼센트
진행률= 7 퍼센트
진행률= 8 퍼센트
진행률= 9 퍼센트
진행률= 10 퍼센트
진행률= 11 퍼센트
진행률= 12 퍼센트
진행률= 13 퍼센트
진행률= 14 퍼센트
진행률= 15 퍼센트
진행률= 16 퍼센트
진행률= 17 퍼센트
진행률= 18 퍼센트
진행률= 19 퍼센트
진행률= 20 퍼센트
진행률= 21 퍼센트
진행률= 22 퍼센트
진행률= 23 퍼센트
진행률= 24 퍼센트
진행률= 25 퍼센트
진행률= 26 퍼센트
진행률= 27 퍼센트
진행률= 28 퍼센트
진행률= 28 퍼센트
진행률= 30 퍼센트
진행률= 31 퍼센트
진행률= 32 퍼센트
진행률= 33 퍼센트
진행률= 34 퍼센트
진행률= 35 퍼센트
진행률= 36 퍼센트
진행률= 37 퍼센트
진행률= 38 퍼센트
진행률= 39 퍼센트
진행률= 40 퍼센트
진행률= 41 퍼센트
진행률= 42 퍼센트
진행률= 43 퍼센트
진행률= 44 퍼센트
진행률= 45 퍼센트
진행률= 46 퍼센트
진행률= 47 퍼센트
진행률= 48 퍼센트
진행률= 49 퍼센트
진행률= 50 퍼센트
진행률= 51 퍼센트
진행률= 52 퍼센트
진행률= 53 퍼센트
진행률= 54 퍼센트
진행률= 55 퍼센트
진행률= 56 퍼센트
진행률= 56 퍼센트
진행률= 57 퍼센트
진행률= 59 퍼센트
진행률= 60 퍼센트
진행률= 61 퍼센트
진행률= 62 퍼센트
진행률= 63 퍼센트
진행률= 64 퍼센트
진행률= 65 퍼센트
진행률= 66 퍼센트
진행률= 67 퍼센트
진행률= 68 퍼센트
진행률= 69 퍼센트
진행률= 70 퍼센트
진행률= 71 퍼센트
진행률= 72 퍼센트
진행률= 73 퍼센트
진행률= 74 퍼센트
진행률= 75 퍼센트
진행률= 76 퍼센트
진행률= 77 퍼센트
진행률= 78 퍼센트
진행률= 79 퍼센트
진행률= 80 퍼센트
진행률= 81 퍼센트
진행률= 82 퍼센트
진행률= 83 퍼센트
진행

In [30]:
clean_train_review[:5]

[['더빙', '진짜', '짜증나다', '목소리'],
 ['포스터', '보고', '초딩', '영화', '오버', '연기', '가볍다', '않다'],
 ['무재', '밓었', '다그', '래서', '보다', '추천'],
 ['교도소', '이야기', '구먼', '솔직하다', '재미', '없다', '평점', '조정'],
 ['사이',
  '몬페',
  '익살스럽다',
  '연기',
  '돋보이다',
  '영화',
  '스파이더맨',
  '늙다',
  '보이다',
  '하다',
  '커스틴',
  '던스트',
  '너무나도',
  '이쁘다',
  '보이다']]

In [25]:
#len(clean_train_review)
len(train_data['document'])

150000

In [37]:
test_file = DATA_IN_PATH + 'ratings_test.txt'
test_data = pd.read_csv(test_file, header=0, delimiter='\t', quoting=csv.QUOTE_NONE)
clean_test_review = []

i = 0
max = len(test_data['document'])
for review in test_data['document']:
    if i % 500 == 0:
        print('진행률= %d 퍼센트' % ((i/max * 100)+1))
        
    if type(review) == str:
        clean_test_review.append(preprocessing(review,True, stopwords))
    else:
        clean_test_review.append([])
    i += 1                  

진행률= 1 퍼센트
진행률= 2 퍼센트
진행률= 3 퍼센트
진행률= 4 퍼센트
진행률= 5 퍼센트
진행률= 6 퍼센트
진행률= 7 퍼센트
진행률= 8 퍼센트
진행률= 9 퍼센트
진행률= 10 퍼센트
진행률= 11 퍼센트
진행률= 12 퍼센트
진행률= 13 퍼센트
진행률= 14 퍼센트
진행률= 15 퍼센트
진행률= 16 퍼센트
진행률= 17 퍼센트
진행률= 18 퍼센트
진행률= 19 퍼센트
진행률= 20 퍼센트
진행률= 21 퍼센트
진행률= 22 퍼센트
진행률= 23 퍼센트
진행률= 24 퍼센트
진행률= 25 퍼센트
진행률= 26 퍼센트
진행률= 27 퍼센트
진행률= 28 퍼센트
진행률= 29 퍼센트
진행률= 29 퍼센트
진행률= 31 퍼센트
진행률= 32 퍼센트
진행률= 33 퍼센트
진행률= 34 퍼센트
진행률= 35 퍼센트
진행률= 36 퍼센트
진행률= 37 퍼센트
진행률= 38 퍼센트
진행률= 39 퍼센트
진행률= 40 퍼센트
진행률= 41 퍼센트
진행률= 42 퍼센트
진행률= 43 퍼센트
진행률= 44 퍼센트
진행률= 45 퍼센트
진행률= 46 퍼센트
진행률= 47 퍼센트
진행률= 48 퍼센트
진행률= 49 퍼센트
진행률= 50 퍼센트
진행률= 51 퍼센트
진행률= 52 퍼센트
진행률= 53 퍼센트
진행률= 54 퍼센트
진행률= 55 퍼센트
진행률= 56 퍼센트
진행률= 57 퍼센트
진행률= 57 퍼센트
진행률= 58 퍼센트
진행률= 60 퍼센트
진행률= 61 퍼센트
진행률= 62 퍼센트
진행률= 63 퍼센트
진행률= 64 퍼센트
진행률= 65 퍼센트
진행률= 66 퍼센트
진행률= 67 퍼센트
진행률= 68 퍼센트
진행률= 69 퍼센트
진행률= 70 퍼센트
진행률= 71 퍼센트
진행률= 72 퍼센트
진행률= 73 퍼센트
진행률= 74 퍼센트
진행률= 75 퍼센트
진행률= 76 퍼센트
진행률= 77 퍼센트
진행률= 78 퍼센트
진행률= 79 퍼센트
진행률= 80 퍼센트
진행률= 81 퍼센트
진행률= 82 퍼센트
진행률= 83 퍼센트
진행률= 84 퍼센트
진

In [33]:
len(clean_test_review)
#len(clean_test_review[:4])

50000

tensorflow를 사용해 기계학습모델에 적용하기 위해서는 단어를 그대로 사용할 수 없으며,
텍스트 데이터인 단어를 수치 데이터로 변환해야 함.
따라서, text_to_sequences 라이브러리를 사용하여 전처리가 끝난 
train_review와 test_review의 각 벡터를 index로 구성된 벡터로 변환.
모든 index는 word_vocab에 저장되어 있음.

In [38]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(clean_train_review)
train_sequence = tokenizer.texts_to_sequences(clean_train_review)
test_sequence = tokenizer.texts_to_sequences(clean_test_review)

word_vocab = tokenizer.word_index

In [39]:
print(clean_train_review[0])
print(train_sequence[0])
#print(word_vocab)
print(len(word_vocab))

['더빙', '진짜', '짜증나다', '목소리']
[314, 11, 165, 460]
41927


In [40]:
from tensorflow.python.keras.preprocessing.sequence import pad_sequences

각 벡터는 서로 길이가 다름. 이 길이를 하나로 통일해야 기계학습모델에 적용할 수 있음.
최대 길이(MAX_SEQUENCE_LENGTH=8)를 정하고, 이 길이보다 긴 벡터는 자르며,
이 길이보다 짧은 벡터는 빈 자리에 0을 추가(padding)한다.

In [41]:
MAX_SEQUNCE_LENGTH = 8

train_inputs = pad_sequences(train_sequence, maxlen=MAX_SEQUNCE_LENGTH, padding='post')
train_labels = np.array(train_data['label'])

In [42]:
print(train_inputs[:5])

[[  314    11   165   460     0     0     0     0]
 [  315    24   415     1  1099    16   472    13]
 [ 1934 23578  1816  4906     2   137     0     0]
 [ 5691    66  7229   135    32     4    17  2988]
 [  807   149     3 13120 18142   781   160   149]]


In [43]:
test_inputs = pad_sequences(test_sequence, maxlen=MAX_SEQUNCE_LENGTH, padding='post')
test_labels = np.array(test_data['label'])

In [44]:
DATA_IN_PATH = './data_in/'
TRAIN_INPUT_DATA = 'nsmc_train_input.npy'
TRAIN_LABEL_DATA = 'nsmc_train_label.npy'
TEST_INPUT_DATA = 'nsmc_test_input.npy'
TEST_LABEL_DATA = 'nsmc_test_label.npy'
DATA_CONFIGS = 'data_configs.json'

In [45]:
data_configs = {}

data_configs['vocab'] = word_vocab
data_configs['vocab_size'] = len(word_vocab)+1

In [46]:
import os

if not os.path.exists(DATA_IN_PATH):
    ok.makedirs(DATA_IN_PATH)

In [47]:
np.save(open(DATA_IN_PATH + TRAIN_INPUT_DATA, 'wb'), train_inputs)
np.save(open(DATA_IN_PATH + TRAIN_LABEL_DATA, 'wb'), train_labels)
np.save(open(DATA_IN_PATH + TEST_INPUT_DATA, 'wb'), test_inputs)
np.save(open(DATA_IN_PATH + TEST_LABEL_DATA, 'wb'), test_labels)

In [48]:
json.dump(data_configs, open(DATA_IN_PATH + DATA_CONFIGS, 'w'), ensure_ascii=False)

In [49]:
import pandas as pd
TRAIN_CLEAN_DATA = 'train_clean.csv'
TEST_CLEAN_DATA = 'test_clean.csv'
clean_train_df = pd.DataFrame({'review':clean_train_review, 
                              'sentiment':train_data['label']})
clean_test_df = pd.DataFrame({'review':clean_test_review, 
                              'sentiment':test_data['label']})
clean_train_df.to_csv(DATA_IN_PATH + TRAIN_CLEAN_DATA, index=False)
clean_test_df.to_csv(DATA_IN_PATH + TEST_CLEAN_DATA, index=False)